# Multi-Node GPU Cluster Configuration
# Copy this file and modify for your cluster setup

cluster:
  name: "gpu-cluster"
  master:
    host: "172.24.27.42"  # Master node IP address
    port: 8080
  
# Node definitions
nodes:
  - node_id: "node001"
    hostname: "172.24.27.42"
    ip: "172.24.27.42"
    port: 8081
    gpu_count: 1
    gpu_type: "RTX 3060"
    
# Network configuration
networking:
  heartbeat_interval: 30  # seconds
  timeout: 60            # seconds
  
# Scheduling policies
scheduling:
  default_policy: "fill_first"  # fill_first, spread, custom
  max_job_time: 3600           # seconds
  
# Security settings (optional)
security:
  enable_ssl: false
  cert_file: ""
  key_file: ""
  
# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "/var/log/mgpu_cluster.log"
